const readlinesync = require ('readline-sync');
const distancia = readlinesync.question ('digite uma distancia em metros: ')
const km = (Number (distancia) / 1.000)
const hm = (Number (distancia) / 100)
const dam = (Number (distancia) / 10)
const dm = (Number (distancia) * 0.1)
const cm = (Number (distancia) * 0.01)
const mm = (Number (distancia) * 0.001)
console.log (`a distância de ${distancia} corresponde a :`)
console.log (` ${km} km`)
console.log (` ${hm} hm`)
console.log (` ${dam} dam`)
console.log (` ${dm} dm `)
console.log (` ${cm} cm`)
console.log (` ${mm} mm`)